version: '2.1'
services:

  # Admin front end
  admin:
    image: flatland-church/flatland-admin-react-public:latest
    container_name: admin
    ports:
      - 6060:80

  # Watchtower - This container watches for updates to the other containers and pulls and restarts them automatically.
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 admin
