version: '2.1'
services:

  # Admin front end
  admin:
    image: flatlandchurch/flatland-admin-react-public:latest
    container_name: admin
    ports:
      - 6060:80

  # Flatland Church main site
  site:
    image: flatlandchurch/flatland-site-reactjs-public:latest
    container_name: site
    restart: on-failure
    ports:
      - 6061:3000

  # Flatland Church main site
  links:
    image: flatlandchurch/flatland-links-js-public:latest
    container_name: links
    ports:
      - 6062:80

  # Watchtower - This container watches for updates to the other containers and pulls and restarts them automatically.
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 admin site links
